# -*- coding: utf-8 -*-
"""ML_week__1__.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B7VftRPpvb2b634iqiamgo1sm0sExVEp
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

# Load the CSV file (replace with your actual file path)
df = pd.read_csv("behaviour_simulation_train.xlsx - Sheet1.csv")  # replace with your actual path

# Basic data inspection
print(df.shape)         # Shows number of rows and columns
print(df.head())        # Displays the first 5 rows
print(df.info())        # Provides summary info of the DataFrame
print(df.isnull().sum())  # Counts missing values in each column

df.dropna(subset=['content', 'username', 'inferred company', 'likes'], inplace=True)
df['media'].fillna('no_media', inplace=True)
df['has_media'] = df['media'].apply(lambda x: x != 'no_media')
df['content'] = df['content'].astype(str).str.strip().str.lower()
df['datetime'] = pd.to_datetime(df['date'], errors='coerce')

import seaborn as sns
import matplotlib.pyplot as plt

sns.histplot(df['likes'], kde=True)
sns.boxplot(x=df['likes'])

df['hour'] = df['datetime'].dt.hour
df['day_of_week'] = df['datetime'].dt.day_name()

df['word_count'] = df['content'].apply(lambda x: len(x.split()))
df['char_count'] = df['content'].apply(len)

"""So some features that can be passed to a api requests are:-     
content---content of the tweet                     
time&date---time and date of the tweet                          
photo/videos---if the tweet has any media                  
word_count---for word coutn
lang---language of the tweet

The frontend can ask the user for similar things as are mentioned in the above cell

preprocessing:- something like                                
converting datetime stamps intoa ctual date and  time                         
handling the laguage of the tweets                             
handlingthe media                            
detecting language

Can we calculate features (e.g., word count, has_media) inside the backend?          
***YES***
"""